export type shopType = {
  capacity: string,
  category: string,
  currency: string,
  description: string,
  duration: string,
  end_date: string,
  id: number,
  images: string,
  short_description: string,
  start_date: string,
  status: string,
  thumbnail: string,
  title: string,
}
